# -*- coding: utf-8 -*-
"""Zomato Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxnWv8CY7Xh6AhjMa1O5I-pBaIrNPJbm

### 1- Data Preparation
"""

import pandas as pd

from google.colab import drive
drive.mount("/content/drive")
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/zomato_analysis.csv')

# Load your dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/zomato_analysis.csv')

# Preliminary cleaning might include handling missing values, fixing data types, etc.
# For example, cleaning the 'rate' column
df['rate'] = df['rate'].replace('NEW', None)
df['rate'] = df['rate'].replace('-', None)
df['rate'] = df['rate'].apply(lambda x : float(x.split('/')[0]) if type(x)==str else x)

"""### 2- Analysis and Exporting Results

--> Price Range Analysis
"""

# Convert 'approx_cost(for two people)' to a numeric type
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'].str.replace(',', '').replace('₹', ''), errors='coerce')

# Now, perform the price range analysis
price_range_analysis = df.groupby(['location', 'cuisines'])['approx_cost(for two people)'].mean().reset_index()

# Export the analysis results
price_range_analysis.to_csv('price_range_analysis_results.csv', index=False)

"""--> Popularity and Engagement Analysis"""

popularity_analysis = df.groupby('name').agg({'votes': 'sum', 'rate': 'mean'}).reset_index()

popularity_analysis.to_csv('popularity_analysis_results.csv', index=False)

"""--> Cuisine and Dish Preferences"""

# This is a bit more complex and might require text analysis on 'dish_liked' and 'cuisines'
# For a simple aggregation:
popular_cuisines = df['cuisines'].value_counts().reset_index().rename(columns={'index': 'cuisine', 'cuisines': 'count'})

popular_cuisines.to_csv('cuisine_preferences_results.csv', index=False)

"""--> Restaurant Accessibility Analysis"""

accessibility_analysis = df.groupby(['location', 'online_order', 'book_table']).size().reset_index(name='count')

accessibility_analysis.to_csv('accessibility_analysis_results.csv', index=False)

"""### 3- Visualization in Power BI"""

# Dashboard on PowerBI file and Export PDF